alertmanager:
  enabled: false
pushgateway:
  eanbled: false

serverFiles:
  prometheus.yaml:
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "neon-notes-app"
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names: ["notes-app"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            target_label: __metrics_path__
            replacement: /metrics
