# Disable components we don't need for this demo
alertmanager:
  enabled: false

pushgateway:
  enabled: false

# Provide custom scrape configurations for the Prometheus server
serverFiles:
  prometheus.yml:
    scrape_configs:
      # Default job to scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Custom job to scrape our neon-notes application
      - job_name: 'neon-notes-app'
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names: ['notes-app']
        relabel_configs:
          # Step 1: Filter and keep only the service named 'notes-svc'
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: 'notes-svc'
          # Step 2: Set the metrics scrape path to '/metrics'
          - source_labels: [__meta_kubernetes_service_name]
            target_label: __metrics_path__
            replacement: /metrics