apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-notes
  namespace: notes-app

spec:
  replicas: 2
  selector:
    matchLabels:
      name: neon-notes
  template:
    metadata:
      labels:
        name: neon-notes
    spec:
      containers:
        - name: notes-cont
          image: kamalv007/neon-notes:latest
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-svc"
            - name: REDIS_PORT
              value: "6379"
