apiVersion: v1
kind: Service
metadata:
  name: notes-svc
  namespace: notes-app

spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
