kind: Service
apiVersion: v1
metadata:
  name: redis-svc
  namespace: notes-app
spec:
  selector:
    app: redis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
