on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ##Job1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build-and-push:
    ##Job2
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker buildx  build -t ${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:${{ github.sha }} . &&  \
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:latest

      # security check
      - name: Run Trivy Vulnerabilty Scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:${{ github.sha }}"
          format: "table"
          exit-code: "0"
          ignore-unfixed: "true"
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/neon-notes:latest
